# Generated by Django 2.1.5 on 2019-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
